apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: customerapp-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: customerapp.flugel.it/v1alpha1
    resource: customerapp
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: Recreate
  - apiVersion: networking.k8s.io/v1beta1
    resource: ingresses
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://customerapp-controller.customerapp/sync
