apiVersion: v1
kind: Service
metadata:
  name: myservice
  annotations:
    autoingress.flugel.it: "on"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: myapp
