apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoingress-controller
  template:
    metadata:
      labels:
        app: autoingress-controller
    spec:
      containers:
      - name: controller
        image: python:3.7
        command: ["python", "-u", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: autoingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: autoingress-controller
spec:
  selector:
    app: autoingress-controller
  ports:
  - port: 80